// website-replication-skill — Design token extractor (Step 2)
//
// Runtime: browser (eval via MCP)
// Output: markdown table of likely design tokens, inferred from
// getComputedStyle on visible elements. Stashed at window.__designTokens.
//
// Use to populate the Visual Tokens table in step 2 without manually
// eyeballing CSS. The script is best-effort statistical — top-N by usage
// count — not a guarantee of the site's official design system.
//
// Side-effect-free: no clicks, no DOM mutations, no network.

(function extractTokens({
  rootSelector = 'body',
  sampleLimit = 1000,
  topN = 10,
} = {}) {
  const root = document.querySelector(rootSelector) || document.body;
  const elements = [...root.querySelectorAll('*')]
    .filter((el) => {
      try {
        const cs = getComputedStyle(el);
        if (cs.display === 'none' || cs.visibility === 'hidden') return false;
        const r = el.getBoundingClientRect();
        return r.width > 0 && r.height > 0;
      } catch (_) {
        return false;
      }
    })
    .slice(0, sampleLimit);

  const hist = {
    color: new Map(),
    backgroundColor: new Map(),
    fontFamily: new Map(),
    fontSize: new Map(),
    fontWeight: new Map(),
    lineHeight: new Map(),
    letterSpacing: new Map(),
    borderRadius: new Map(),
    boxShadow: new Map(),
    padding: new Map(),
    margin: new Map(),
    gap: new Map(),
    borderColor: new Map(),
    borderWidth: new Map(),
  };

  function bump(map, key) {
    if (!key) return;
    // Keep pure black here: it is usually the dominant text color and belongs
    // in the per-category histograms. Black/white are filtered later, but only
    // from the brand palette, where they carry no signal.
    const trivial = ['normal', 'auto', 'none', '0px', '0px 0px 0px 0px', 'rgba(0, 0, 0, 0)'];
    if (trivial.includes(key)) return;
    map.set(key, (map.get(key) || 0) + 1);
  }

  for (const el of elements) {
    try {
      const cs = getComputedStyle(el);
      bump(hist.color, cs.color);
      bump(hist.backgroundColor, cs.backgroundColor);
      bump(hist.fontFamily, cs.fontFamily);
      bump(hist.fontSize, cs.fontSize);
      bump(hist.fontWeight, cs.fontWeight);
      bump(hist.lineHeight, cs.lineHeight);
      bump(hist.letterSpacing, cs.letterSpacing);
      bump(hist.borderRadius, cs.borderRadius);
      bump(hist.boxShadow, cs.boxShadow);
      bump(hist.padding, cs.padding);
      bump(hist.margin, cs.margin);
      bump(hist.gap, cs.gap);
      bump(hist.borderColor, cs.borderColor);
      bump(hist.borderWidth, cs.borderWidth);
    } catch (_) {}
  }

  function topEntries(map, n) {
    return [...map.entries()].sort((a, b) => b[1] - a[1]).slice(0, n);
  }

  const out = [];
  out.push('<!-- Generated by website-replication-skill/references/design-tokens.js -->');
  out.push(`<!-- ${new Date().toISOString()} · ${location.href} · ${elements.length} visible elements sampled -->`);
  out.push('');

  // Master table
  out.push('## Token histogram (top values by usage count)');
  out.push('');
  out.push('| Category | Top values |');
  out.push('| --- | --- |');
  for (const [cat, map] of Object.entries(hist)) {
    const top = topEntries(map, topN);
    if (top.length === 0) {
      out.push(`| ${cat} | — |`);
      continue;
    }
    const cell = top.map(([v, n]) => `\`${v}\` (${n})`).join('<br>');
    out.push(`| ${cat} | ${cell} |`);
  }

  // Color palette extraction — merge color + bg + border, drop transparent
  out.push('');
  out.push('## Color palette');
  out.push('');
  out.push('Combined color usage across `color`, `background-color`, `border-color`. Transparent and pure black/white filtered.');
  out.push('');
  out.push('| Color | Combined count |');
  out.push('| --- | --- |');
  // Brand palette: drop fully-transparent colors and pure black/white. Match
  // alpha-0 only on `rgba(...)` so opaque colors with a zero channel — red
  // `rgb(255, 0, 0)`, yellow `rgb(255, 255, 0)` — are NOT mistaken for transparent.
  const isTransparent = (c) => c === 'transparent' || (/^rgba\(/.test(c) && /,\s*0\)$/.test(c));
  const palette = new Map();
  for (const key of ['color', 'backgroundColor', 'borderColor']) {
    for (const [c, n] of hist[key].entries()) {
      if (isTransparent(c) || c === 'rgb(0, 0, 0)' || c === 'rgb(255, 255, 255)') continue;
      palette.set(c, (palette.get(c) || 0) + n);
    }
  }
  for (const [c, n] of [...palette.entries()].sort((a, b) => b[1] - a[1]).slice(0, 15)) {
    out.push(`| \`${c}\` | ${n} |`);
  }

  // Spacing scale guess — extract unique px values from padding/margin/gap
  out.push('');
  out.push('## Spacing scale guess');
  out.push('');
  const spacings = new Set();
  for (const key of ['padding', 'margin', 'gap']) {
    for (const v of hist[key].keys()) {
      for (const m of v.match(/-?\d+(?:\.\d+)?px/g) || []) {
        const px = parseFloat(m);
        if (px > 0 && px <= 96) spacings.add(px);
      }
    }
  }
  out.push(`Distinct px values 1–96 seen: ${[...spacings].sort((a, b) => a - b).join(', ') || '(none)'}.`);
  out.push('');
  out.push('A clean design system usually shows a small set (e.g., 4 / 8 / 12 / 16 / 24 / 32). A long list suggests ad-hoc spacing.');

  // Font family count
  out.push('');
  out.push(`## Font families: ${hist.fontFamily.size} distinct`);
  out.push('');
  for (const [v, n] of topEntries(hist.fontFamily, 5)) {
    out.push(`- \`${v}\` (${n})`);
  }

  const result = out.join('\n');
  console.log(result);
  window.__designTokens = result;
  return { bytes: result.length, sampled: elements.length, output: result };
})();
